Feature/splash screen
folkehelseinstituttet/Fhi.Koronasertifikat.Verifikasjon.App pull request #135
Opened 2022-10-06 11:53 UTC by manetcom

2022-10-06 12:20 UTC, tslaNetcompany commented on FHICORC.Core/Services/DecoderServices/CertificateRevocationService.cs
> +            if(token is DCCPayload payload)
add space between if statement and ()

2022-10-06 12:24 UTC, tslaNetcompany commented on FHICORC.Core/Services/DecoderServices/CertificateRevocationService.cs
> +        public bool CheckHashInRevocationBatchesAsync(IEnumerable<RevocationBatch> revocationBatches, string uciBase64EndodedHash, string countryCodeUciBase64EndodedHash, string signatureBase64Encode
isParallel = false

2022-10-06 12:43 UTC, tslaNetcompany requested changes

2022-10-06 12:43 UTC, tslaNetcompany commented on FHICORC.Core/Services/Interface/IFetchRevocationBatchesFromBackednService.cs
> +    public interface IFetchRevocationBatchesFromBackednService
IFetchRevocationBatchesFromBackendService

2022-10-06 12:43 UTC, tslaNetcompany commented on FHICORC.Core/Data/Models/RevocationBatch.cs
> +    public class RevocationBatch : DatabaseEntityBase
add constructor

2022-10-06 12:43 UTC, tslaNetcompany commented on FHICORC.Core/Services/DecoderServices/FetchRevocationBatchesFromBackednService.cs
> +    //    public class Monitor
Is this needed?

2022-10-06 12:43 UTC, tslaNetcompany commented on FHICORC.Core/Services/DecoderServices/FetchRevocationBatchesFromBackednService.cs
> +        //static async void Run()
Is this needed?

2022-10-06 12:43 UTC, tslaNetcompany commented on FHICORC.Core/Services/Utils/BloomFilterUtils.cs
> +        public int m { get; set; }
PascalCase

2022-10-06 12:43 UTC, tslaNetcompany commented on FHICORC.Core/Services/Utils/MobileUtils.cs
> +        public static bool ContainsCertificateFilterMobile(string uciHash, string countryCodeUciHash, string signatureHash, IEnumerable<RevocationBatch> revocationBatches, List<BucketItem> bloomFilte
bool isParallel = true

2022-10-06 12:43 UTC, tslaNetcompany commented on FHICORC/App.xaml.cs
> +        private readonly IFetchRevocationBatchesFromBackednService _fetchRevocationBatchesFromBackednService;
_fetchRevocationBatchesFromBackendService

2022-10-06 12:43 UTC, tslaNetcompany commented on FHICORC/App.xaml.cs
> +            _fetchRevocationBatchesFromBackednService = IoCContainer.Resolve<IFetchRevocationBatchesFromBackednService>();
_fetchRevocationBatchesFromBackednService

2022-10-13 10:22 UTC, teddy515 approved these changes

2022-10-13 10:53 UTC, merged